ul = -inf
uu = inf
xtr_l = -inf
xtr_u = inf
utr_l = -inf
utr_u = inf
gamma_init = 1.0
alpha_mul = 0.5
margin_ls = 1e-2
tol_stat = 1e-2
tol_primal = 1e-4
tol_dual = 1e-4
tol_comp = 1e-4
tol_interp = 1.0
eps_reg = 1e-6
eps_fd = 1e-8
maxiter_sqp = 1000
maxiter_qp = 1000
maxiter_ls = 20
is_verbose = true
save_bestsol = true
